### ISSUE TITLE
Assigning lots of variables

### ISSUE THREAD

**Issue by msachi** [facn5/WeatherAPIGet#16]
Instead of creating lots of variables, you could just create one object (e.g. 'weatherData') and store all of your information in it. It's more memory efficient and easier to read.

https://github.com/facn5/WeatherAPIGet/blob/e24731f9f9e777ab6113b6876c952d7e9e5f5e86/models/app.js#L20-L27

**Comment by msachi** [comment]
```
let data = {
  description: data["weather"][0]["description"],
  temp: data["main"]["temp"],
  ...
}
```

**Comment by faris114** [comment]
@msachi issue solved !
